camera:
  id: 0
  mode: 2
  flip_method: 0

image:
  width: 1280
  height: 720
  topic: "/camera_0"

video:
  title: "camera_0.mp4"
  frame_rate: 30

rosbag:
  start: 0
  filename: " "
  directory: " "