camera:
  id: 1
  mode: 0
  flip_method: 0

image:
  width: 1280
  height: 720
  topic: "/camera_1"

video:
  title: "camera_1.mp4"
  frame_rate: 20

rosbag:
  start: 0
  filename: "2023-02-28-08-44-41.bag"
  directory: "/home/satin/rosbags"