video:
  title: "camera_1.mp4"
  frame_rate: 20.0
  width: 1280
  height: 720

image_topic: "/camera_1"

start_rosbag: 1
rosbag_filename: "2023-02-27-13-11-41.bag"
rosbag_directory: "/media/lachlanmares/Vx1000 Ext SSD/rosbags"
