camera:
  id: 1
  mode: 3
  flip_method: 0

image:
  width: 960
  height: 540
  topic: "/camera_1"

video:
  title: "camera_1.mp4"
  frame_rate: 30

rosbag:
  start: 0
  filename: "2023-02-28-08-44-41.bag"
  directory: "/home/satin/rosbags"