video:
  title: "camera_1.mp4"
  frame_rate: 30.0
  width: 2048
  height: 1536

image_topic: "/camera_1"

start_rosbag: 1
rosbag_filename: "2023-02-27-13-11-41.bag"
rosbag_directory: "/home/satin/rosbags"
